### ISSUE TITLE
zend error on magento v1.7.0.2

### ISSUE THREAD

**Issue by hgati** [colinmollenhour/Cm_RedisSession#103]
magento category page error

SQLSTATE[42S22] [1054] Unknown column 'FLOOR((ROUND((e.min_price) * 0.000933593495, 2)) / 10) + 1' in 'order clause', query was: SELECT FLOOR((ROUND((e.min_price) * 0.000933593495, 2)) / 10) + 1 AS `range`, COUNT(*) AS `count` FROM `catalog_product_index_price` AS `e`
 INNER JOIN `catalog_category_product_index` AS `cat_index` ON cat_index.product_id=e.entity_id AND cat_index.store_id=2 AND cat_index.visibility IN(2, 4) AND cat_index.category_id='303' WHERE ( e.website_id = '1' ) AND ( e.customer_group_id = 0) AND (e.min_price IS NOT NULL) GROUP BY FLOOR((ROUND((e.min_price) * 0.000933593495, 2)) / 10) + 1 ORDER BY `FLOOR((ROUND((e`.`min_price) * 0`.`000933593495, 2)) / 10) + 1` ASC

#0 /var/www/htdocs/project/root/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute()
#1 /var/www/htdocs/project/vendor/magento/zendframework1/library/Zend/Db/Statement.php(323): Varien_Db_Statement_Pdo_Mysql->_execute()
#2 /var/www/htdocs/project/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute()

php-redis-session-abstract based on zendframework v1.12
php-redis-session-abstract doesn't work on magento v1.7.0.2 (zendframework v1.11.1)

**Comment by colinmollenhour** [comment]
I fail to see how this is related to Cm_RedisSession...

**Comment by hgati** [comment]
i added on my composer.json - it's sql error
![snap1](https://cloud.githubusercontent.com/assets/6913728/22392709/b941a2a0-e53f-11e6-9c73-c18f82f8e3e5.jpg)


i removed on my composer.json - it works
![snap2](https://cloud.githubusercontent.com/assets/6913728/22392701/ab6fbfcc-e53f-11e6-91f7-1bca12dd5b46.jpg)

**Comment by colinmollenhour** [comment]
Sorry, I have no idea why that would be.

**Comment by ProxiBlue** [comment]
http://stackoverflow.com/questions/35049778/tag-aggregation-data-index-process-unknown-error/42584628#42584628
