### ISSUE TITLE
FYI: m1 issue with versiosn past 1.12

### ISSUE THREAD

**Issue by ProxiBlue** [colinmollenhour/Cm_RedisSession#105]
Don't really need a fix, as it would most likely not be worth your time, but maybe a mention in readme will suffice to lock down to 1.12 for m1 installs.

Unless there is an easy fix ;)

http://stackoverflow.com/questions/35049778/tag-aggregation-data-index-process-unknown-error/42584628#42584628

**Comment by colinmollenhour** [comment]
Thanks for the report, @ProxiBlue. It seems the main issue is that the abstract library specifically lists zendframework as a requirement in [composer.json](https://github.com/colinmollenhour/php-redis-session-abstract/blob/master/composer.json#L14). I think this can just be removed since it doesn't actually appear to use any ZF code...

**Comment by colinmollenhour** [comment]
Would you mind testing the latest version and letting me know if the issue is fixed?

Thanks again!

**Comment by ProxiBlue** [comment]
Looks all good to me now :)

Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.022 seconds
Analyzed 16952 packages to resolve dependencies
Analyzed 10406 rules to resolve dependencies
  - Installing colinmollenhour/credis (1.7)
    Loading from cache
    Extracting archive

    REASON: colinmollenhour/php-redis-session-abstract v1.3.2 requires colinmollenhour/credis ~1.6 -> satisfiable by colinmollenhour/credis[1.6, 1.7].

  - Installing colinmollenhour/php-redis-session-abstract (v1.3.2)
    Downloading: 100%         
    Extracting archive

    REASON: colinmollenhour/magento-redis-session 2.0.3 requires colinmollenhour/php-redis-session-abstract ~1.3.2 -> satisfiable by colinmollenhour/php-redis-session-abstract[v1.3.2].

  - Removing colinmollenhour/magento-redis-session (1.12)
  - Installing colinmollenhour/magento-redis-session (2.0.3)
    Downloading: 100%         
    Extracting archive

    REASON: Required by the root package: Install command rule (install colinmollenhour/magento-redis-session 2.0|install colinmollenhour/magento-redis-session 2.0.1|install colinmollenhour/magento-redis-session 2.0.2|install colinmollenhour/magento-redis-session 2.0.3|install colinmollenhour/magento-redis-session 2.0|install colinmollenhour/magento-redis-session 2.0.1|install colinmollenhour/magento-redis-session 2.0.2|install colinmollenhour/magento-redis-session 2.0.3)
