### ISSUE TITLE
Concurrent requests make session write back unreliable when modifying the session in one of those requests

### ISSUE THREAD

**Issue by hkuiyo** [colinmollenhour/Cm_RedisSession#107]
We are using Cm_RedisSession with magento 2.1

We created a piece of JavaScript that runs after the addcart Ajax call, which does another Ajax call to a custom controller. When that request is done, we do a redirect (with JavaScript) to the shipping page in magento.

The custom controller is putting a property in the session that we are reading on the shipping page. 

We noticed that, with these 4 requests (main request + the request to addcart + request to our custom controller + redirect), some strange concurrency issues seem to be happening.

In our logging we could see that the session that is sent to redis actually contains our attribute, but a few msec later we see that the session that does not yet contain our attribute is sent to redis, overwriting our operation and therefore not saving the property in the session! 

We feel that magento or redis is still processing something, because if we put a setTimeout of 5000 msec between the Ajax request, second Ajax request and the redirect, it is working just fine. 

Of course we want to have a better solution to this problem than using the mentioned timeouts. Any suggestions on what configuration to use, or maybe how we can prevent the session from overwriting?

**Comment by hkuiyo** [comment]
It could also be that the controller action that is putting the property in the session is still sending data to redis, while the other Ajax request is also using a session (the old one, without the property) and in the end also sending it's session (again, without the property) to redis.

**Comment by colinmollenhour** [comment]
The locking should enforce that all of these requests are completed serially.. What is your config?

**Comment by jurgenbrouwer** [comment]
In addition:
Both requests are custom. We have AjaxCall1 and AjaxCall2 which run immediately after eachother:
```
$.ajax({
  url: '/AjaxCall1',
  method: 'post',
  data: {storeId: storeId, productId: productId},
}).done(function (e) {
  $.ajax({
    url: '/AjaxCall2',
    method: 'post',
    data: {shippingmethod: 'pickup'}
  }).done(function (e) {
    location.href = 'someOtherUrl';
  });
});
```

The change we noticed is missing in the session is made in AjaxCall2.
When the browser navigates to another page after the second ajax call, the change in the session was not persisted. We can see this happening in the redis-cli monitor. There is a second save which overwrites our changes.

It appears something is happening in the first call which is not finished when starting the session of the second call. 
Or the second call opens two sessions. But we tried to debug that and we think that is not happening.

Our config:
```
...
'session'         =>
        [
            'save'  => 'redis',
            'redis' =>
                [
                    'host'                  => '127.0.0.1',
                    'port'                  => '6901',
                    'password'              => 'password',
                    'timeout'               => '2.5',
                    'persistent_identifier' => '',
                    'database'              => '2',
                    'compression_threshold' => '2048',
                    'compression_library'   => 'gzip',
                    'log_level'             => '1',
                    'max_concurrency'       => '6',
                    'break_after_frontend'  => '5',
                    'break_after_adminhtml' => '30',
                    'first_lifetime'        => '600',
                    'bot_first_lifetime'    => '60',
                    'bot_lifetime'          => '7200',
                    'disable_locking'       => '0',
                    'min_lifetime'          => '60',
                    'max_lifetime'          => '2592000',
                ],
        ],
...
```


_We have workaround for it now: add a 500ms delay before the second call._

**Comment by colinmollenhour** [comment]
I'm not convinced this is a bug in the session backend code as it could be also an issue with the way the application updates the session data. If you crank up the log level you should see the sessions being locked and read/written sequentially and if not then there is indeed a bug.

**Comment by jurgenbrouwer** [comment]
Alright, the thing is we see two writes in redis-cli monitor. One with our change and one without our change. But we're not sure where the second write is coming from.
We load our sessions with injection, which should mean Magento will give a reference to the same session...
We enabled the logging in the Redis session class and noticed the constructor is called a lot. But the register savehandler is only called once. Which would mean that a save is only triggered once.

Not sure where to go from here. For now we can live with the workaround. Maybe it's a bug in Magento, or some other issue in our setup.
If I ever get some time to investigate this issue further, or if I run into this issue again, I'll let you know what our findings are.

**Comment by SergeyCherepanov** [comment]
Hi @jurgenbrouwer and @colinmollenhour I found similar issue in magento 2.0.8 with full page cache feature enabled. If FPC enabled magento sets session id cookie only on non cached requests. Like ajax or shopping cart. And if you do the parallel requests it is will be cause multiple sessions initialization. You can se example on this screenshot http://pub.srv.today/scherepanov/Monosnap_2017-03-22_01-33-45.png. Swatches requests started befor I added product to cart. But response received after ajax cart request and it override my session cookie. So it's application issue, not a Cm_RedisSession.
