### ISSUE TITLE
Composer deploy NOT working just the  MODMAN one

### ISSUE THREAD

**Issue by obsergiu** [colinmollenhour/Cm_RedisSession#109]
Hi, 

When I run composer update there are dependencies not being deployed.  
I have the following setup:

- Magento 1.9.2
- PHP5.5  (but i tested also with PHP5.6)
- Composer 1.4.1

I'm using the packages.firegento.com so my composer looks like this:

```
{
  "name": "me/test-dev",
  "type": "magento-module",
  "minimum-stability": "dev",
  "require": {
      "colinmollenhour/magento-redis-session": "*",
       ...
  },
  "repositories": [
    { "type": "composer", "url": "https://packages.firegento.com" },
    { "type": "composer", "url": "https://satis.test.dev"}
  ],
  "extra":{
    "installer-paths": {
      ".modman/{$vendor}_{$name}/": ["type:magento-module"]
    }
   },
   "config":{
      "discard-changes": true,
      "secure-http": false
    }
}

```

after i run `composer update` there's a script which runs:

`modman deploy-all --force`

that should make sure that all modules are deployed.

**The tricky part:** it seems when I run composer update it will NOT load all the dependencies and my tree structure will look like this:

![image](https://cloud.githubusercontent.com/assets/1486717/24196534/02f06898-0ef6-11e7-8984-ea2121c5a7c3.png)

I'm not a guru so I don't claim everything I'm doing is perfect but during 2 days of testings I reached the EOL. 

While if I run MODMAN clone i get everything I need:

![image](https://cloud.githubusercontent.com/assets/1486717/24196848/3458c0e6-0ef7-11e7-983b-26b05077e218.png)

Please, can somebody have a look into it and let me know what I'm missing.

Thank you

**Comment by colinmollenhour** [comment]
Doesn't composer put the dependencies in a "vendor" directory and handle autoloading with it's own autoloader? In this case it is fine for these directories to be empty, right?

**Comment by obsergiu** [comment]
Thank you for your answer, 

Indeed, you pointed out very well - I was assuming I had an autoloader which was loading the whole dependencies.
