### ISSUE TITLE
Issue with connection

### ISSUE THREAD

**Issue by ewallkrishnaprakash** [colinmollenhour/Cm_RedisSession#112]
We are facing the below error on redis connection. We are using the php7.0, apache2 and niginx as our  server. Please help us to resolve the issue.

Connection to Redis 127.0.0.1:6379 failed after 2 failures.Last Error : (0) Failed to parse address "127.0.0.1:6379/1

**Comment by LukeHandle** [comment]
Hey @ewallkrishnaprakash, take a look at https://github.com/colinmollenhour/Cm_RedisSession/issues/111 It looks like there is a temporary workaround of not defining the persistent string (I assume you currently have this set to "1").
