### ISSUE TITLE
Modman and /lib/

### ISSUE THREAD

**Issue by studio2f** [colinmollenhour/Cm_RedisSession#114]
I could be doing something wrong here (quite possible) but it seems to me that when doing a fresh install of the latest version via modman, all the files from /lib/ are not included. Is that correct?

**Comment by colinmollenhour** [comment]
credis is linked to app/code/local/Credis so that it will superscede the bundled version in lib/Credis

**Comment by studio2f** [comment]
Colin,

Thanks for the response and thanks for everything you've done for Magento! As I said, I've probably made a mistake. After a clean modman install, per the instructions I run 

```
php .modman/Cm_RedisSession/migrateSessions.php --test
```

and the result is that lib/Cm/RedisSession/ doesn't exist (which it doesn't on my install). 

```
fatal error: require_once(): Failed opening required '/home/XXX/public_html/lib/Cm/RedisSession/Handler/ConfigInterface.php' 
(include_path='/home/XXX/public_html/app/code/local:/home/XXX/public_html/app/code/community:/home/XXX/public_html/app/code/core:/home/XXX/public_html/lib:.:/usr/local/lib/php') 
in /home/XXX/public_html/.modman/Cm_RedisSession/code/Model/Session/Handler.php on line 32
```

I *believe* modman didn't build the symbolic link back to .modman/Cm_RedisSession/code/lib/src/Cm/RedisSession/Handler/ConfigInterface.php

**Comment by colinmollenhour** [comment]
Ahh, I forgot the utility scripts use a different class.. I remove the require_statements which should allow the autoloader to do it's thing.
