### ISSUE TITLE
Question about encryption ?

### ISSUE THREAD

**Issue by waghanza** [colinmollenhour/Cm_RedisSession#116]
Hi,

I try to take a lookup about session data store in `redis`.

I'm on a **Magento** `1.9` with `Cm_RedisSession` **enabled**.

On a **local** `redis` my session's data are store in plain text. However on a **remote** `redis` data seems to be binaries.

How can I decode those data ?

Regards,

**Comment by waghanza** [comment]
I finally use `_decodeData` in **Cm_RedisSession_Model_Session** to decode those data

**Comment by LukeHandle** [comment]
Hey. Is the data prefixed with "gz:"? It's likely GZip'ed compresses data?

**Comment by waghanza** [comment]
@LukeHandle effectively. I have some time **gz** as a prefix.
I have use the  `_decodeData` (https://github.com/colinmollenhour/Cm_RedisSession/blob/1.15/code/Model/Session.php#L599) since it check for compression type, e.g :
+ lzf
+ lzma
+ gzip
+ lz4
