### ISSUE TITLE
Magento 2 Update

### ISSUE THREAD

**Issue by mberkman** [colinmollenhour/Cm_RedisSession#118]
I am working on a proyect in Magento 1.x wich has installed RedisSession pluging. My question is if there is a version supported for Magento 2.x, or if there is an alternative plugin instead of this one.

**Comment by colinmollenhour** [comment]
I believe Magento 2 bundles Redis session support out of the box. They helped refactor it into the [php-redis-session-abstract](https://github.com/colinmollenhour/php-redis-session-abstract) library for just this reason.
