### ISSUE TITLE
mod_fcgid: stderr: PHP Fatal error:

### ISSUE THREAD

**Issue by bbtimx** [colinmollenhour/Cm_RedisSession#119]
I try to install the Cm_RedisSession Modul manually but I got the following error:

```
mod_fcgid: stderr: PHP Fatal error:  
Class Cm_RedisSession_Model_Session_Config contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods 
(Cm\\RedisSession\\Handler\\ConfigInterface::getSentinelServers, Cm\\RedisSession\\Handler\\ConfigInterface::getSentinelMaster, Cm\\RedisSession\\Handler\\ConfigInterface::getSentinelVerifyMaster, ...) 
in /var/www/share/shop/htdocs/app/code/local/Cm/RedisSession/Model/Session/Config.php on line 197
```

My Folder Structure:

app/code/local
--Cm/RedisSession
----Cm_RedisSession Files
----lib/src/Cm/RedisSession
------php-redis-session-abstract FIles
--Credis
----credis Files

**Comment by colinmollenhour** [comment]
Sound like you have an outdated version of the php-redis-session-abstract library.

**Comment by bbtimx** [comment]
Downloaded yesterday: php-redis-session-abstract-1.2.2.zip

**Comment by colinmollenhour** [comment]
The latest is 1.3.3.. Looks like 1.2.2 is sorted at the top of the list though.. Not sure why, but using 1.3.3 should fix your issue.

**Comment by colinmollenhour** [comment]
Actually 1.3.4..

**Comment by Morgy93** [comment]
@colinmollenhour 
I got the exact same error:
colinmollenhour/cache-backend-redis: 1.10.2
colinmollenhour/credis: 1.8.2
colinmollenhour/magento-redis-session: 2.1.4
colinmollenhour/php-redis-session-abstract: 1.3.5

Since `colinmollenhour/php-redis-session-abstract` seems to be the latest version I cannot solve the issue.

**Comment by bbtimx** [comment]
Try Credis 1.9.1

**Comment by Morgy93** [comment]
Crap, forgot to update composer before posting versions (was still debugging :D)
Well, actually I'm at:
colinmollenhour/cache-backend-redis: 1.10.4
colinmollenhour/credis: 1.9.1

But the error persists.

**Comment by Morgy93** [comment]
Well, it cannot work.

https://github.com/colinmollenhour/Cm_RedisSession/commit/49f889bfe35d6104bf90b33320abd8540099346e#diff-776c754f0c89ac46a265370fefc2d242

There are my missing methods, which were introduced in 2.1.5, but latest release is 2.1.4

I'll update manually to 2.1.6 and see if it works.

**Comment by colinmollenhour** [comment]
Glad you got it working, sorry for the versioning debacle..

**Comment by mabigo** [comment]
gosh i was so close to rollback my recent deployment. thx @Morgy93
