### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by mlippie** [colinmollenhour/Cm_RedisSession#120]
I am getting the following PHP error when trying to run the compilation process.

`2017/07/05 12:48:02 [error] 20721#20721: *13046 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'Cm\RedisSession\Handler' not found in /data/web/public/includes/src/Cm_RedisSession_Model_Session.php:58
Stack trace:
#0 /data/web/public/includes/src/Amasty_Fpc_Model_Fpc_Front.php(470): Cm_RedisSession_Model_Session->__construct()
#1 /data/web/public/includes/src/Amasty_Fpc_Model_Fpc_Front.php(617): Amasty_Fpc_Model_Fpc_Front->startSession()
#2 /data/web/public/includes/src/Amasty_Fpc_Model_Fpc_Front.php(1403): Amasty_Fpc_Model_Fpc_Front->ignore()
#3 /data/web/public/includes/src/Mage_Core_Model_Cache.php(687): Amasty_Fpc_Model_Fpc_Front->extractContent(false)
#4 /data/web/public/includes/src/__default.php(21278): Mage_Core_Model_Cache->processRequest()
#5 /data/web/public/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#6 /data/web/public/index.php(83): Mage::run('', 'store')
#7 {main}
  thrown in /data/web/public/includes/src/Cm_RedisSession_Model_Session.php on line 58" while reading response header from upstream, client: 91.183.86.70, server: demeestertest.hypernode.io, request: "GET / HTTP/2.0", upstream: "fastcgi://127.0.0.1:9000", host: "demeestertest.hypernode.io"`

I installed the module with modman. I am on the latest version of Cm_RedisSession and am on version 1.9.3.3 of magento.

**Comment by colinmollenhour** [comment]
I notice your path is `includes/src/Cm_RedisSession_Model_Session.php`.. Is this the Magento "compiler" extension or some third-party extension which replaces the default autoloader? I personally have used Aoe_ClassPathCache which works fine, but have not tried any others and do not have time to help you debug them, unfortunately.

**Comment by mlippie** [comment]
It is the Magento compiler. The problem dissapeared when we did a full reinstall of Magento.

**Comment by iget-esoares** [comment]
@colinmollenhour I'm with the same issue when try to compile a magento installation with your package.

My logs are showing the following errors at every page try, and the server gives 500 error.

> 2017-11-06T18:14:37+00:00 ERR (3): Warning: include(/var/www/vhosts/newolders.com/store.newolders.com/includes/src/Cm\RedisSession\Handler.php): failed to open stream: No such file or directory  in /var/www/vhosts/newolders.com/store.newolders.com/includes/src/Varien_Autoload.php on line 94
> 2017-11-06T18:14:37+00:00 ERR (3): Warning: include(): Failed opening '/var/www/vhosts/newolders.com/store.newolders.com/includes/src/Cm\RedisSession\Handler.php' for inclusion (include_path='/var/www/vhosts/newolders.com/store.newolders.com/includes/src:.:/usr/share/php')  in /var/www/vhosts/newolders.com/store.newolders.com/includes/src/Varien_Autoload.php on line 94
>

**Comment by colinmollenhour** [comment]
Please see my previous response: https://github.com/colinmollenhour/Cm_RedisSession/issues/120#issuecomment-313141163
