### ISSUE TITLE
Session file name does not match expected pattern: sess_\w+

### ISSUE THREAD

**Issue by anhuy1989** [colinmollenhour/Cm_RedisSession#121]
Hello Magento experts,

    Session file name does not match expected pattern: sess_\w+    
I get this message when run migrateSession.php on terminal in Magento version 1.8.0.0 . 
I have to remove that regex to migrate session.
Do you have any suggestion to solve this one?

Thanks in advance,
Huy

**Comment by colinmollenhour** [comment]
Perhaps there is a file in var/session that doesn't match that pattern? Or else it is probably looking in the wrong directory for some reason? Unfortunately I can't really help you much more than this...

**Comment by colinmollenhour** [comment]
I improved the error message so that should help you discover and fix the issue.

**Comment by anhuy1989** [comment]
Thanks Colin. You are the best.
