### ISSUE TITLE
Session Lost PHP 7.0 + Suhosin

### ISSUE THREAD

**Issue by xdexter** [colinmollenhour/Cm_RedisSession#122]
Hello, 

I'm using Magento 1.9.x with Nginx/PHP-FPM 7.0, if i enable suhosin module (more specifically "suhosin.session.encrypt" option) my backend session lost randomically, if i press f5 multiple times the session down and i need login again.

There are some incompatibility with module and suhosin?

Thank you!

**Comment by xdexter** [comment]
Ahh, and i'm using Redis (db backend), in files backend this problem don't occur.

**Comment by colinmollenhour** [comment]
> The patient says "Doctor, it hurts when I do this." "Then don't do that!"

Disable `suhosin.session.encrypt`. It is mentioned in the README that lzf doesn't work and you get bad compression. It really shouldn't be necessary if you are not on shared hosting and you shouldn't be running an ecommerce site on shared hosting.

**Comment by xdexter** [comment]
Hi @colinmollenhour ,

Hmm right, i read this in documentation but i don't use lzf, see:

>         <session_save>db</session_save>
        <redis_session>
                <host>localhost</host>
                <port>6379</port>
                <password></password>
                <timeout>2.5</timeout>
                <db>8</db>
                <compression_threshold>0</compression_threshold>
                <compression_lib>gzip</compression_lib>
                <log_level>1</log_level>
        </redis_session>

If i use gzip i need disable suhosin.session.encrypt too?

Regards

**Comment by xdexter** [comment]
@colinmollenhour ?

**Comment by LukeHandle** [comment]
@xdexter based on the previous reply, it's probably going to be along lines of try with all compression disabled.

Then reference back to the last bit:

> It really shouldn't be necessary if you are not on shared hosting and you shouldn't be running an ecommerce site on shared hosting.

**Comment by xdexter** [comment]
Hi @LukeHandle ,

Right, it's true, i'm not using shared hosting, but i think that it's imporant for security, BUT if you say that are imcompatible, Ok, i will disable, do you understand me?

Regards

**Comment by LukeHandle** [comment]
I'm honestly not sure if gzip and the security mode are compatible or not. The security requirement should focus on network ACL to the Redis instance etc.

I suggest trying the combination of options and seeing if it works. It might be a case of either have the security bit or have the compression.

**Comment by xdexter** [comment]
Hi @LukeHandle ,

Right, i think that has some problem with module + php7, because if i use PHP 5.5 all works (With suhosin.session.encrypt enabled).

I already searched on internet but i not found anything about this ;/

**Comment by colinmollenhour** [comment]
It looks like there is a separate project for [suhosin on PHP 7](https://github.com/sektioneins/suhosin7) and it is in *alpha*. So I'd report the bug there if you really want this fixed, but honestly it's just going to hurt performance and not give you any security benefit unless you have a specific concern you're not disclosing. It's not like passwords are stored in the sessions, for the most part just a user id, some user agent data and a few other non-sensitive bits. I do however recommend looking at `session.hash_*` and `session.entropy_*` to avoid collisions if you run a high-traffic site (not for security purposes, the defaults are pretty sufficient for security purposes IMO).

**Comment by xdexter** [comment]
Hi @colinmollenhour ,

Ok i got it, perfect, thank you for your attention!

Regards
