### ISSUE TITLE
Upgrade to 2.1.4 Fatal error

### ISSUE THREAD

**Issue by TimVroom** [colinmollenhour/Cm_RedisSession#123]
Hi there.

After updating the module to version 2.1.4 it throws me some errors:

```
Fatal error: Class Cm_RedisSession_Model_Session_Config contains 4 abstract methods and must therefore be declared abstract or implement the remaining methods (Cm\RedisSession\Handler\ConfigInterface::getSentinelServers, Cm\RedisSession\Handler\ConfigInterface::getSentinelMaster, Cm\RedisSession\Handler\ConfigInterface::getSentinelVerifyMaster, ...)
```

This is related to the colinmollenhour/php-redis-session-abstract upgrade to 1.3.5 because it changed it config interface. It now includes the sentinel methods.

So those 2 modules don't work well together anymore.

**Comment by colinmollenhour** [comment]
Ahh, right it seems I merged the sentinel branch on that repo but not this one.. I just tagged 2.1.5 which merges the sentinel branch on this repo and should fix the issue.
