### ISSUE TITLE
Session migration from MySQL

### ISSUE THREAD

**Issue by timciep** [colinmollenhour/Cm_RedisSession#125]
Can someone please add some documentation for migration from MySQL-based (in addition to file-based) session storage?

In a test-run of the `migrateSessions_mysql_redis.php` script, on a MySQL sessions table of 1M+ rows, the script was on pace to take over 24 hours to run.

Is there any way to migrate only critical sessions, such as those associated with quotes?

Thanks!

**Comment by colinmollenhour** [comment]
You could do your own data cleanup before starting the migration. There are no plans to do any of that in the migration script but pull requests are always welcome.
