### ISSUE TITLE
Installs into app/code/local/Cm/RedisSession/code if app/code/local/Cm/RedisSession exists

### ISSUE THREAD

**Issue by kirkmadera** [colinmollenhour/Cm_RedisSession#127]
There are instances where we reinstall modules by clearing the vendor directory sometimes and then rerunning `composer install`. When you do this with this module, it creates a new directory named "code" within "app/code/local/Cm/RedisSession". You should be able to run `composer install` multiple times with the same result each time. This has resulted in bad production deployments on a number of projects and a lot of confusion for us over time.

The best fix for this, I believe, is to make the source directory name match the target directory name.

**Comment by kirkmadera** [comment]
The same also happens for the credis submodule.

**Comment by ramsaybell** [comment]
@kirkmadera We've come across the same issue, I see you have resolved this in the open PR - https://github.com/colinmollenhour/Cm_RedisSession/pull/128
