### ISSUE TITLE
After enabling Compilation, Magento breaks

### ISSUE THREAD

**Issue by i6media** [colinmollenhour/Cm_RedisSession#131]
Hi,

After installing Cm_RedisSession via Modman, everything works fine.
But when I compile, I get the following error:

_PHP Fatal error: Uncaught Error: Class 'Cm\\RedisSession\\Handler' not found in /var/www/vhosts/(...)/httpdocs/includes/src/Cm_RedisSession_Model_Session.php:58_

Any idea what this could be?

Thanks in advance.

**Comment by colinmollenhour** [comment]
Sorry, the Compiler feature is not supported.

**Comment by MageSuper** [comment]
@colinmollenhour Can you reopen this issue, I believe making this extension compatible with compile mode is not that difficult, so I was just wondering what's preventing you from supporting it?

I even have tried to compile it, and I ended with the same error, but when you view the relevant files you can see you are using require_once to specific files etc... so if you assign an absolute path it should work just fine.

Looking forward to hearing from you.

Sincerely,

**Comment by colinmollenhour** [comment]
@MageSuper I will be happy to consider merging a pull request. Thanks!
