### ISSUE TITLE
Compression is not disabled when compression_threshold is set to 0

### ISSUE THREAD

**Issue by nemphys** [colinmollenhour/Cm_RedisSession#133]
The way the session's private compression threshold variable is set ($this->_compressionThreshold =  $this->config->getCompressionThreshold() ?: self::DEFAULT_COMPRESSION_THRESHOLD;) makes it take the default (2048) value if set to 0 in the xml.

Just noticed this while debugging something irrelevant (and all this time I thought I had compression disable :-) ).

**Comment by Quazz** [comment]
I think you need to set compression_lib to none in order to disable compression.
