### ISSUE TITLE
Implement read-only (lockless) session

### ISSUE THREAD

**Issue by nemphys** [colinmollenhour/Cm_RedisSession#134]
Since I am struggling with delayed AJAX requests due to session locking, I am wondering if it would make sense to implement an option (set through a special parameter using define() maybe?) that would change the session to read-only mode (this would mean disable locking on read and do nothing on write).
This way, in cases when we are sure that the session data will not be changed by the current request, there would be a considerable response speed increase.

I think it would be a nice feature; I can make a PR if you think it's worth implementing.

**Comment by nemphys** [comment]
I have already implemented it and it seems to work fine (at least it solves my problem).
@colinmollenhour please tell me if you are interested for a PR.

**Comment by cmtickle** [comment]
@nemphys I'd be really interested in seeing your implementation of this feature please.

**Comment by nemphys** [comment]
@cmtickle since I don't maintain this in a separate repo, you can check the attached zip (the implementation is in a separate module for easier maintenance).
After you install the module, all you have to do is call

$this->setFlag('', Nemphys_RedisSession_Model_Session::FLAG_READ_ONLY, 1);

inside the preDispatch method of your controller.
[Nemphys_RedisSession.zip](https://github.com/colinmollenhour/Cm_RedisSession/files/1592916/Nemphys_RedisSession.zip)

**Comment by cmtickle** [comment]
Many thanks for supplying that.

**Comment by seansan** [comment]
+1 is this something we can merge?

**Comment by hassanas** [comment]
@colinmollenhour  This is quite serious issue from several years, please review the PR and gave your valuable comments on it, as you are the absolute final authority on it.

**Comment by colinmollenhour** [comment]
I've merged your PR for the php-redis-session-abstract project adding support for the $readOnly parameter. Please submit a PR for this project as well.

**Comment by nemphys** [comment]
Just created the PR, but I see that there are merge conflicts (I had created the branch a while ago, something must have changed in Session.php in the meanwhile).
Please check.

**Comment by nemphys** [comment]
OK, a new PR has just been created with no merge conflicts, please review and (hopefully) merge.

**Comment by colinmollenhour** [comment]
Thanks, merged and tagged.

**Comment by hassanas** [comment]
Thanks @colinmollenhour
