### ISSUE TITLE
Different Users Sharing Sessions

### ISSUE THREAD

**Issue by PapaDragonov** [colinmollenhour/Cm_RedisSession#139]
Hey guys,
this is not a certain code issue but more or less just a question: Does someone here have an idea how the problem that our users are randomly sharing their sessions may probably be caused by this module or generally by using redis as session storage in magento? We know that this is not a common problem with this module since we are using it successfully in other shops. But in one we have the mentioned problem. And the problem is solved if we deactivate the module and save the sessions in the filesystem.
Any ideas? Thanks in advance.
Best regards,
SW

**Comment by colinmollenhour** [comment]
Make sure your PHP config has a sufficiently large session hash algorithm and bytes of entropy. PHP generates the id and the session backend just loads the id that is requested so I don't see how id collisions could be the fault of the session backend.
