### ISSUE TITLE
Snappy compression and magento admin success login redirect to login 

### ISSUE THREAD

**Issue by aldovalentr** [colinmollenhour/Cm_RedisSession#141]
I have magento 1.7 versione and have installed session storage ONLY with redis.
When I login in backend admin page after correct login I'm redirect to login admin page.
If I select gZip compression all work perfectlly. 
With snappy site is very very fast

**Comment by colinmollenhour** [comment]
Snappy compression is not implemented, you must build a PHP extension which provides snappy_compress method. This is not trivial so I suggest you use lzf and install extension with pecl.
