### ISSUE TITLE
Incorrect php-redis-session-abstract version dependency in composer.json

### ISSUE THREAD

**Issue by ajbonner** [colinmollenhour/Cm_RedisSession#146]
Changes to php-redis-session-abstract supporting readonly sessions were released in tag 1.4.0. 

However in the current version of CM_RedisSession this library dependency is pinned to "~1.3.5" 
https://github.com/colinmollenhour/Cm_RedisSession/blob/master/composer.json#L13. 

This means you have the Cm\RedisSession\Handler constructor called with 3 arguments from Cm_RedisSession, but the library installed, only supports the two arguments. 

https://github.com/colinmollenhour/php-redis-session-abstract/blob/v1.3.5/src/Cm/RedisSession/Handler.php#L254

I've manually installed everything and the functionality is perfect but installing from composer is not working due to the out of date dependency.

Thanks for all your work on this module and the readonly feature is a great addition!

**Comment by colinmollenhour** [comment]
Ahh, thanks. Fixed and tagged 2.3.1.

**Comment by ajbonner** [comment]
This works for me, thanks! 👍
