### ISSUE TITLE
performance problems...

### ISSUE THREAD

**Issue by sholdowa** [colinmollenhour/Cm_RedisSession#16]
I have a multi-vps Magento setup which is currently sharing a dedicated redis data store across 6 workers - each dedicated solely to processing php.

After recently being asked to install New Relic to investigate performance problems, it is reporting that one of the main culprits is the redis session stuff, with an example trace showing 48% in Credis_Client::__call, and 40% in Cm_RedisSession_Model_Session::read. The big worry was that the complete /catalog/category/view 'transaction' took just under 80s to complete!

Now it looks like the newrelic.so PHP plugin is  based on xdebug, which is known to mess with performance anyway, so I am taking this with a pinch of salt.

When I run perf tests via the cli from the same server, all runs fine.
The redis server is not overloaded, although network traffic may be in excess of 40Mbit/s.
I have updated to the latest RedisSession plugin.
I have updated redis to  2.6.14, and it is now not saving session details to disk.
I have updated phpredis to current

My current config is...

```
    <session_save><![CDATA[db]]></session_save>
    <redis_session>                      
        <host>192.168.132.86</host>
        <port>6379</port>
        <timeout>5.0</timeout>            
        <persistent></persistent>        
        <db>0</db>
        <compression_threshold>0</compression_threshold>  
        <compression_lib>gzip</compression_lib>              
        <log_broken_locks>0</log_broken_locks>              
        <max_concurrency>8</max_concurrency>
        <break_after_frontend>5</break_after_frontend>     
        <break_after_adminhtml>30</break_after_adminhtml>
        <bot_lifetime>7200</bot_lifetime>                   
    </redis_session>
```

I upped the break_after_frontend to 5s to see if that would help - maybe there was a timeout at 2.5 and the delay was caused by updating sessions to the database?? -and have tried both persistent and non-persistent connections.

monitoring of the redis process and underlying servers themselves shows no problems - responding to change in loads, and nowhere near cpu/mem capacity.

If you have any ideas, please let me know!

Cheers,

Steve

EDIT: I currently seem to have c. 50,000 sessions stored in redis, but only have an access rate of c. 4/s. Is there a simple way I can be more agressive in clearing theold session details out?

**Comment by wsteinbach** [comment]
We find out an (maybe) interesting aspect:

Long running PHP processes caused a problem in Redis session handlung in connection with old redis server version.

First we checked that a Magento API request took 1 second on our stage system and 30 seconds on live. We traced it via New Relic. The entry looked like

`
Cm_RedisSession_Model_Session::read	1	30,100 ms	98%
`

Same with some not cached search requests:

`Cm_RedisSession_Model_Session::read	1	30,100 ms	98%`
`Mage_Catalog_Model_Layer::getFilterableAttributes	3	11,500 ms	32%`
`Bubble_Elasticsearch_Model_Resource_Fulltext_Collection::addSearchFilter	1	10,700 ms	30%`

Problems accoured with redis 2.6.17 and not under 2.8.9.

**Comment by parhamr** [comment]
@wsteinbach that 30-second timing reads to me as a session lock. Please review the configuration options and consider disabling locking or decreasing timeouts.

**Comment by wsteinbach** [comment]
Thank you very much. It works with

`
<disable_locking>1</disable_locking>
`

BTW:
The Docu https://github.com/colinmollenhour/Cm_RedisSession is a little bit confusing to me:

`
<disable_locking>0</disable_locking>                 
`

suggests to me '0' disables locking but I think '1' = true does it?!

**Comment by colinmollenhour** [comment]
Locking is considered a core feature so it was safer to add "disable_locking" with 0 being the implicit value which retains backwards compatibility than use "enable_locking" in which case backwards compatibility would be broken. "Disable: yes" means disabled is pretty clear IMO.

I don't know what your original issue was, perhaps a fatal error was occurring and causing sessions to be left locked?

**Comment by ewaveluke** [comment]
Would be great to get some further information on this. We get these occurring quite regularly with no identifiable pattern. 

![f0lseht](https://cloud.githubusercontent.com/assets/15317141/11140972/974f373c-8a34-11e5-9464-02931c8f04f4.png)

What are your thoughts around disabling locking @colinmollenhour? There aren't any fatal errors causing sessions to remain locked from what we've investigated so far.

**Comment by colinmollenhour** [comment]
With locking disabled multiple requests could overwrite each other's session data. If that is fine with you then disabling will certainly resolve your issue.

What is "quite regularly"? If it is 1:100,000 hits then I wouldn't say that is quite regular.. If it is quite regular then you should be able to collect more data to go by for tracking down the issue. E.g. if it happens while persisting database to disk then you could setup replication and disable persistence on the master.

**Comment by Bobspadger** [comment]
We are also experiencing this with the Session::read.

Sometimes in mundane calls;
![screenshot 2015-11-16 10 49 45](https://cloud.githubusercontent.com/assets/1614970/11180082/eaa2695a-8c4f-11e5-884a-48dd2c7594d2.png)

ALWAYS on return from Sagepay using ebizmarts sagepay suite pro.

![screenshot 2015-11-16 10 50 11](https://cloud.githubusercontent.com/assets/1614970/11180096/fd291da8-8c4f-11e5-877d-36e5f67b01b5.png)

I'm tempted to give the disable_locking fix a go, but concerned we could cause more problems than we have currently?

**Comment by colinmollenhour** [comment]
Interesting. Nothing comes to mind regarding why a particular extension would be able to trigger a session read issue, but it sounds like you've at least identified a starting point to dig further. If you don't want to dig further then either disable locking just for those requests somehow (e.g. define the constant in index.php when the request path is matched) or set a much lower `break_after_frontend` to just reduce how long it waits for the lock before breaking it.

**Comment by Bobspadger** [comment]
we're going to give the upgraded module a go and deploy that tomorrow. It seems to suggest it will work on our staging site, but this is not under the same user load as production (obviously!)

Will know more tomorrow!

**Comment by parhamr** [comment]
:+1: for a fairly low `break_after_frontend` value. I’ve had better results with that config as low as `4`.

**Comment by Bobspadger** [comment]
updating to the latest version of the code has stopped our return time from being 30s + ~4s down to ~4s in total.

Much better and as anticipated.

**Comment by MWilkinson** [comment]
Hi @Bobspadger,
   we've been following this thead for a little while now, and can you clarify what code you've updated to the latest versions.

Many Thanks

**Comment by Bobspadger** [comment]
we went from Magento 1.9.1.0 codebase to the latest on github :)

**Comment by Bobspadger** [comment]
0 app/code/community/Cm/RedisSession/Model/Session.php
+47 -15 app/code/community/Cm/RedisSession/etc/config.xml
+32 -0 app/etc/modules/Cm_RedisSession.xml
+2 -0 lib/Credis/.gitignore
+375 -55 lib/Credis/Client.php
+317 -0 lib/Credis/Cluster.php
+23 -0 lib/Credis/LICENSE
+171 -0 lib/Credis/README.markdown
+239 -0 lib/Credis/Sentinel.php
+23 -0 lib/Credis/composer.json
+21 -0 lib/Credis/phpunit.xml
+3 -0 lib/Credis/tests/.gitignore
+224 -0 lib/Credis/tests/CredisClusterTest.php
+173 -0 lib/Credis/tests/CredisSentinelTest.php
+29 -0 lib/Credis/tests/CredisStandaloneClusterTest.php
+8 -0 lib/Credis/tests/CredisStandaloneSentinelTest.php
+37 -0 lib/Credis/tests/CredisStandaloneTest.php
+351 -0 lib/Credis/tests/CredisTest.php
+35 -0 lib/Credis/tests/SetUpBefore.php
+35 -0 lib/Credis/tests/TearDownAfter.php
+100 -0 lib/Credis/tests/keys.test
+5 -0 lib/Credis/tests/redis-2.conf
+5 -0 lib/Credis/tests/redis-3.conf
+5 -0 lib/Credis/tests/redis-4.conf
+6 -0 lib/Credis/tests/redis-auth.conf
+5 -0 lib/Credis/tests/redis-master.conf
+6 -0 lib/Credis/tests/redis-sentinel.conf
+6 -0 lib/Credis/tests/redis-slave.conf
+6 -0 lib/Credis/tests/redis-socket.conf
+9 -0 lib/Credis/tests/redis_config.json
+1 -0 lib/Credis/tests/sentinel_config.json

**Comment by MWilkinson** [comment]
@Bobspadger Many thanks... that appears to have solve the issue for us as well...

**Comment by dardrone** [comment]
For anyone looking on here to know WHY @Bobspadger saw times being decreased from 30s -> ~4s, I believe it is because the default of 30sec was being used due to this issue:

https://github.com/colinmollenhour/Cm_RedisSession/issues/61

**Comment by urifoox** [comment]
> With locking disabled multiple requests could overwrite each other's session data. If that is fine with you then disabling will certainly resolve your issue.

Can you please elaborate on what this means? Is it that one user can overwrite another user's or that one user's session could be overwritten by concurrent requests from their browser (loading page + AJAX). Either way, how would you test for this in production and how risky is it to enable it?

**Comment by colinmollenhour** [comment]
Necro... :)

The session id is the key that is locked so it is the latter. Likelihood depends o your application but in Magento there is not all that much important data in the sessions, mostly the session messages and the quote id.

Closing conversation.
