### ISSUE TITLE
Passing glue string after array is deprecated. Swap the parameters in colinmollenhour/credis/Client.php on line 1414

### ISSUE THREAD

**Issue by MountainX** [colinmollenhour/Cm_RedisSession#172]
Magento 2 is failing to start. The logs show this error:

> Deprecated Functionality: implode(): Passing glue string after array is deprecated. Swap the parameters in vendor/colinmollenhour/credis/Client.php on line 1414

I have a standard Redis installation. There is **no custom code** in the site. Redis was installed in the usual way according to these [Magento Dev Docs][1].

Here's the code referenced by the error message:

       1406     /**
       1407      * Build the Redis unified protocol command
       1408      *
       1409      * @param array $args
       1410      * @return string
       1411      */
       1412     private static function _prepare_command($args)
       1413     {
       1414         return sprintf('*%d%s%s%s', count($args), CRLF, implode(array_map(array('self', '_map'), $args), CRLF), CRLF);
       1415     }

**Has anyone run into this error yet?** Is there a solution (other than disabling Redis)?

Version info: 

 - Magento ver. 2.3.3 
 - redis 5.0.7 
 - redis-cli 5.0.7

  [1]: https://devdocs.magento.com/guides/v2.3/config-guide/redis/redis-pg-cache.html

**Comment by colinmollenhour** [comment]
This is related to running PHP 7.4. It was fixed here: https://github.com/colinmollenhour/credis/pull/131
I just tagged it as 1.11.1

Magento2 will need to pull in the latest version.

**Comment by kirkmadera** [comment]
Confirmed that this no longer occurs in Magento 2.4.0 on PHP 7.4 which was just GA released today

**Comment by moni921** [comment]
I have magento 2.4 setup and getting above issue with php 7.4. Please help

**Comment by kirkmadera** [comment]
If you upgraded from <7.4, you might try manually clearing redis.

    redis-cli flushall

of

    telnet localhost 6379
    flushall
