### ISSUE TITLE
Magento 2 switching to Laminas instead of Zend (ZF2)

### ISSUE THREAD

**Issue by frno-morita** [colinmollenhour/Cm_RedisSession#176]
Hi, recently Magento 2 has started working towards replacing Zend (ZF2) with Laminas instead starting at Magento 2.4: [Migrate ZF2 components to Laminas components #26436](https://github.com/magento/magento2/pull/26436/files). Will this affect this module and are there any works in that case to support the Laminas project also?

[It currently does not seem like they plan to drop the dependency on Zend Framework 1](https://github.com/magento/magento2/pull/26436/files#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L40), but I am still asking since this change in Magento 2 will affect many of our systems in different ways.

**Comment by colinmollenhour** [comment]
It appears Laminas for now is fully BC with Zend and Magento has decided to keep a Zend compatibility layer in-place, so for now I don't see a need to change anything here.

**Comment by frno-morita** [comment]
Okay, that is good to know. Can we keep this issue open in order to track the progress of Magento 2 going forward in the case where they would start deprecating the `Zend Framework 1` mirror package? This would probably only start being a problem in that scenario.

**Comment by colinmollenhour** [comment]
I believe Magento 2 already includes this library in the official release so it would already be in their best interests to not break anything so I would expect they either take maintenance fully in-house or just submit PRs here directly.
