### ISSUE TITLE
Separate read-only instance from read/write instance

### ISSUE THREAD

**Issue by rcurrington** [colinmollenhour/Cm_RedisSession#180]
I don't see anything in the default config for separating out a read only connection.  I'm using AWS Elasticache and have a cluster setup for caching. AWS is able to provide endpoints for read/write and read only.  As of right now, all read and writes are happening on the same instance.  Is there any additional configuration that can be added to support this functionality?

**Comment by joshua-bn** [comment]
Use your configuration endpoint. https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Endpoints.html#Endpoints.Find.RedisCluster

**Comment by rcurrington** [comment]
Thanks for the tip! Is there a max version of the redis engine that this plugin supports?

**Comment by joshua-bn** [comment]
I'm running Redis 6 just fine. Redis is really good at being backwards compatible. I just upgraded a server from Redis 1.x to Redis 6 without any code changes.

**Comment by rcurrington** [comment]
Thank you

**Comment by joshua-bn** [comment]
BTW, you are probably way overprovisioned if you're using a cluster. A single node will run thousands of cmd/sec just fine.
