### ISSUE TITLE
missing ConfigInterface

### ISSUE THREAD

**Issue by tmotyl** [colinmollenhour/Cm_RedisSession#181]
Class `Cm_RedisSession_Model_Session_Config` implements `\Cm\RedisSession\Handler\ConfigInterface`.
However I can't fin the ConfigInterface.php file.
In some places it is also required like:

`require_once __DIR__.'/../lib/src/Cm/RedisSession/Handler/ConfigInterface.php`

Is the file missing, or is the issue on my side?

Similar story is regarding `Cm\RedisSession\Handler\LoggerInterface`

**Comment by colinmollenhour** [comment]
These are in the dependency https://github.com/colinmollenhour/php-redis-session-abstract
