### ISSUE TITLE
Native Magento Redis Session extension

### ISSUE THREAD

**Issue by dandrikop** [colinmollenhour/Cm_RedisSession#185]
Hello,

In the past, I had installed the extension Cm_RedisSession on Magento 1.7.0.2. The relevant extension had been installed under the directory /app/code/local/Cm/RedisSession. Afterwards, I upgraded to Magento 1.9.4.5 which has native support for Redis sessions. So, I ended up with having code under both the following directories:

/app/code/local/Cm/RedisSession
/app/code/community/Cm/RedisSession

The file /app/etc/modules/Cm_RedisSession.xml seems to be that of Magento 1.9.4.5 which has codePool=community, and not the one of the extension Cm_RedisSession I got from github which had codePool=local. However, after conducting some checks I got the impression that the Cm_RedisSession extension actually used by my Magento installation is the initial one installed under /app/code/local/Cm, and not the native one installed under /app/code/community/Cm.

So, I have 3 questions:

1. How can I make the native one be used by Magento installation?
2. Which of the above extensions System > Configuration > Advanced > Cm_RedisSession=Enable corresponds to?
3. I know that the Cm_RedisSession I got from github does not support Compiler. Can I enable Magento compiler with the native Cm_RedisSession extension of Magento 1.9.4.5?

**Comment by colinmollenhour** [comment]
I recommend upgrading to OpenMage as Magento is EOL.
