### ISSUE TITLE
How can I install a specific version of this module via modman?

### ISSUE THREAD

**Issue by norgeindian** [colinmollenhour/Cm_RedisSession#192]
As we still have a modman structure in our projects, I need to install version 2.4.0.
But how do I do this? I don't see any version parameter in the docs, when I clone the repo.

**Comment by colinmollenhour** [comment]
You can add additional args:
`modman clone https://github.com/colinmollenhour/Cm_RedisSession.git -- --branch 2.4.0`
I never tried it but it looks like it should work.

Or you can [download](https://github.com/colinmollenhour/Cm_RedisSession/archive/refs/tags/2.4.0.zip) and unzip then run `modman deploy`.
Or just checkout the 2.4.0 tag after cloning.

**Comment by norgeindian** [comment]
@colinmollenhour, thanks a lot for this fast reply.
Would you mind, adding this to the README? (see https://github.com/colinmollenhour/Cm_RedisSession/pull/193)
At least for me, it was not really obvious how to do this.

**Comment by colinmollenhour** [comment]
Thanks for the PR!
