### ISSUE TITLE
lib/* in modman file is too generic

### ISSUE THREAD

**Issue by triplesek** [colinmollenhour/Cm_RedisSession#43]
using `lib/*` in the `modman` file causes https://github.com/magento-hackathon/magento-composer-installer to add `/lib` to `.gitignore` when configured with:
```json

{
    ...
    "extra":{
        "auto-append-gitignore": true
    }
    ...
}
```

**Comment by colinmollenhour** [comment]
Fixed by 1e405cb928a151d0723fdad3e3d4c66753272203
