### ISSUE TITLE
Removes lib directory!

### ISSUE THREAD

**Issue by babanski** [colinmollenhour/Cm_RedisSession#54]
Typical installation:

modman clone git://github.com/colinmollenhour/Cm_RedisSession.git
Cloning into 'Cm_RedisSession'...
remote: Counting objects: 555, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 555 (delta 0), reused 0 (delta 0), pack-reused 552
Receiving objects: 100% (555/555), 147.54 KiB, done.
Resolving deltas: 100% (217/217), done.
Submodule 'lib/Credis' (git://github.com/colinmollenhour/credis.git) registered for path 'lib/Credis'
Cloning into 'lib/Credis'...
remote: Counting objects: 692, done.
remote: Total 692 (delta 0), reused 0 (delta 0), pack-reused 692
Receiving objects: 100% (692/692), 182.50 KiB, done.
Resolving deltas: 100% (394/394), done.
Submodule path 'lib/Credis': checked out '7bd47b61fc3dad28aa881de45c71026256ad27cc'
 Applied: code                            app/code/community/Cm/RedisSession
 Applied: Cm_RedisSession.xml             app/etc/modules/Cm_RedisSession.xml

########## NOTICE BELOW:########################
WARNING: Removing conflicting directory: xx/lib
 Applied: lib/Credis                      lib/

The end result:  ./lib directory that is inside the modman root is deleted even though it can have some files or directories inside. 
Please fix this ASAP

**Comment by colinmollenhour** [comment]
Yikes, sorry about that.. Fixed.
