### ISSUE TITLE
table report_viewed_product_index is missing visitor_id (NULL)

### ISSUE THREAD

**Issue by seansan** [colinmollenhour/Cm_RedisSession#55]
Hi, recently when testing we notices something strange. 

On dev with redis_session = off, we see that the table report_viewed_product_index has the column *visitor_id* always with an ID from session

On our prod server with Cm_RedisSession turned on we see that the column *visitor_id* is always NULL ...... 

We noticed because an extension uses the value from *visitor_id* .... can you verify this?

Expected behavior: *visitor_id* colum is populated

[IMAGE BELOW SHOWS OUR DEV SERVER, PROD IS SAME RESULT WITH COLUMN NULL]
![image](https://cloud.githubusercontent.com/assets/652395/7029514/7b858ef8-dd5e-11e4-8756-d3cfb2460107.png)

**Comment by colinmollenhour** [comment]
I cannot confirm this behavior on my production systems and cannot think of any reason why Cm_RedisSession would cause such behavior.
