### ISSUE TITLE
Getting a lot of "Did not write session for ID..."

### ISSUE THREAD

**Issue by fredrikjahr** [colinmollenhour/Cm_RedisSession#56]
Example:
Did not write session for ID 0m8vk5mqaq33dqok3sqdbfk5h1: another process took the lock.

How can I avoid this?

This is my settings:

        <redis_session>                       
            <host>127.0.0.1</host>            
            <port>6379</port>
            <password></password>             
            <timeout>2.5</timeout>            
            <persistent></persistent>         
            <db>0</db>                        
            <compression_threshold>2048</compression_threshold>  
            <compression_lib>gzip</compression_lib>              
            <log_level>7</log_level>               
            <max_concurrency>6</max_concurrency>                 
            <break_after_frontend>5</break_after_frontend>       
            <break_after_adminhtml>30</break_after_adminhtml>
            <first_lifetime>600</first_lifetime>                 
            <bot_first_lifetime>60</bot_first_lifetime>          
            <bot_lifetime>7200</bot_lifetime>                    
            <disable_locking>0</disable_locking>                 
            <min_lifetime>60</min_lifetime>                      
            <max_lifetime>2592000</max_lifetime>                 
        </redis_session>

**Comment by colinmollenhour** [comment]
Increase break_after_* or disable locking or ignore the errors if they seem to be for legitimate reasons.
