### ISSUE TITLE
Errors in system.log

### ISSUE THREAD

**Issue by fredrikjahr** [colinmollenhour/Cm_RedisSession#57]
I'm getting the following errors:

ERR (3): Recoverable Error: Object of class Credis_Client could not be converted to string  in /home/httpd/dohieco/dohieco.se/app/code/community/Cm/RedisSession/Model/Session.php on line 374

This is the code from that line:

                    $this->_log(sprintf(
                        "Successfully broke lock for ID %s after %.5f seconds (%d attempts). Lock: %d\nLast request of broken lock: %s",
                        $sessionId, (microtime(true) - $timeStart), $tries, $lock, $this->_redis->hGet($sessionId, 'req')
                    ), Zend_Log::INFO);

**Comment by colinmollenhour** [comment]
Ahh, the client was in pipeline mode at the time that code is called.. Thanks for the report!
