### ISSUE TITLE
Does not connect at all!

### ISSUE THREAD

**Issue by devdesco-ceo** [colinmollenhour/Cm_RedisSession#60]
I am trying to make your Cm_RedisSession work on Magento 1.9.1.1 but at no avail. It is installed through modman along with Cm_Cache_Backend_Redis which is working OK, but the  Cm_RedisSession does not even try to connect to Redis server! I am also using different databases fr the store, tried to tweak few settings, but again - at no avail!

Please help.

**Comment by colinmollenhour** [comment]
The github project is for reporting bugs and making pull requests for improvements, not for tech support. If the README instructions are inadequate then please report the problems found.
