### ISSUE TITLE
Incorrect session_name when instantiating session model

### ISSUE THREAD

**Issue by Persata** [colinmollenhour/Cm_RedisSession#61]
Hi Colin,

I think I might have found an issue with the use of session_name() inside the constructor for the session model class which is leading to the wrong values being used for the ``$_breakAfter`` variable.

The Cm_RedisSession_Model_Session is constructed on line 65 of ``Mage_Core_Model_Session_Abstract_Varien::start``:

```php
$sessionResource = Mage::getResourceSingleton('core/session');
```

Inside the constructor, ``$_breakAfter`` is being assigned like so:

```php
$this->_breakAfter = ((float) $config->descend('break_after_'.session_name()) ?: self::DEFAULT_BREAK_AFTER);
```

However, the session name isn't set until much later (after the session model has already been constructed) inside ``Mage_Core_Model_Session_Abstract_Varien::start`` on line 120:

```php
if (!empty($sessionName)) {
    $this->setSessionName($sessionName);
}
```

The call to ``session_name()`` inside the Cm_RedisSession_Model_Session constructor resolves to 'PHPSESSID', which then causes the config lookup to search for a config path of 'break_after_PHPSESSID'.

This then resolves to false, which causes the result of the ternary to default to the value of ``self::DEFAULT_BREAK_AFTER`` (30) instead of the values set in the config for 'break_after_frontend' and 'break_after_adminhtml'.

I've checked this on EE1.14.1 and Community 1.9.2 to make sure it wasn't something in my setup.

If this is the case, I'm happy to make a pull request to resolve it - perhaps add a ``_getBreakAfter()`` method that will wait to calculate the break after value until it's actually needed, and at that point the the session name will be set correctly?

Thanks!

**Comment by parhamr** [comment]
:clap: for a great writeup!

**Comment by colinmollenhour** [comment]
Yes, good catch! I must not have tested non-default values.. Thanks for the report and a pull request would be much appreciated.

**Comment by Persata** [comment]
I've opened a pull request, but I see now that @phpdave11 has beaten me to it!

**Comment by colinmollenhour** [comment]
Thanks everyone (including @phpdave11) for finding and fixing the issue. A new version 1.11 has been tagged after a PR was merged.
