### ISSUE TITLE
Migrate sessions from Memcached to Redis

### ISSUE THREAD

**Issue by theycallmepepper** [colinmollenhour/Cm_RedisSession#66]
I see there are two supported options for migration session from file/db -> redis.  Are there any supported methods for migrating sessions from Memcached -> redis?

**Comment by colinmollenhour** [comment]
No, but I'd be happy to accept a pull request. :)

**Comment by theycallmepepper** [comment]
I'll make a note of this and see if I can get something worked up in the near future.

**Comment by chuangbo** [comment]
@theycallmepepper This script could be a hint
https://github.com/colinmollenhour/Cm_RedisSession/blob/master/migrateSessions_mysql_redis.php

**Comment by theycallmepepper** [comment]
@chuangbo That should definitely help lead me in the right direction.  Looking at it and the docs for Zend_Cache_Backend_Memcached I should be able to get something working.  Hopefully I'll have a bit of free time to work on it soon.

**Comment by samm-git** [comment]
I dont think that it is ever possible. There is no (by design) official way to get all memcached content from it.

**Comment by colinmollenhour** [comment]
@samm-git Which is a great reason to never use memcached for anything other than a cache. :)

Googling around it appears there is a method using the "stats" feature but it is not guaranteed to work 100%.

**Comment by samm-git** [comment]
@samm-git agree. Actually there are 2 options: memcached as a software or memcached as protocol, what is supported by many other servers, from the Couchbase to MySQL. In this case you typically can do whatever you want with data using native interfaces. 
And yes, it should be possible to write poor man converter using 'stats items' and 'stats cachedump' commands.

**Comment by samm-git** [comment]
btw, another problem with memcached converted is that there are 2 different extensions with it own format: pecl-memcache and pecl-memcached (libmemcache based). AFAIK magento out of the box works only with pecl-memcache, so probably this is only needed. Magento 2 allows to use any registred session handler, so both extensions could be used.
