### ISSUE TITLE
Cm_RedisSession & Cm_Cache_Backend_Redis

### ISSUE THREAD

**Issue by sasoriza** [colinmollenhour/Cm_RedisSession#67]
I am using both extensions alongside this Redis Manager: https://github.com/steverobbins/Magento-Redismanager) and noticed the following behavior:

If I only include the edits for Cm_RedisSession in my local.xml, the Redis Manager will list the session database as being in use. As soon as I also include the Cm_Cache_Backend_Redis edits, both databases will be listed in the Redis Manager but the session db will remain empty.

Is this a problem with the Redis Manager or am I doing something wrong? This is the related code in my local.xml I am trying:

        
        <cache>
          <backend>Cm_Cache_Backend_Redis</backend>
          <backend_options>
            <server>127.0.0.1</server>
            <port>6379</port>
            <persistent></persistent>
            <database>1</database>
            <password></password>
            <force_standalone>1</force_standalone>
            <connect_retries>1</connect_retries>
            <read_timeout>10</read_timeout>
            <automatic_cleaning_factor>0</automatic_cleaning_factor>
            <compress_data>1</compress_data>
            <compress_tags>1</compress_tags>
            <compress_threshold>20480</compress_threshold>
            <compression_lib>gzip</compression_lib>
            <use_lua>0</use_lua>
          </backend_options>
        </cache>
          
        <session_save>db</session_save>
        <redis_session>
            <host>127.0.0.1</host>
            <port>6379</port>
            <password></password>
            <timeout>2.5</timeout>
            <persistent></persistent>
            <db>2</db>
            <compression_threshold>2048</compression_threshold>
            <compression_lib>gzip</compression_lib>
            <log_level>4</log_level>
            <max_concurrency>6</max_concurrency>
            <break_after_frontend>5</break_after_frontend>
            <break_after_adminhtml>30</break_after_adminhtml>
            <first_lifetime>600</first_lifetime>
            <bot_first_lifetime>60</bot_first_lifetime>
            <bot_lifetime>7200</bot_lifetime>
            <disable_locking>0</disable_locking>
            <min_lifetime>60</min_lifetime>
            <max_lifetime>2592000</max_lifetime>
        </redis_session>

**Comment by colinmollenhour** [comment]
Sounds like a bug with Redismanager...

Cool tool. However, in a production environment do you really want anyone to have the ability to flush cache and sessions from the admin UI? Seems like this is something that should be needed extremely rarely and considering the potential destructiveness  do you really even want it? For monitoring I'd recommend something like Munin or one of the other countless monitoring tools to monitor Redis directly.

**Comment by sasoriza** [comment]
I never used it to flush the cache, only for monitoring. I will take a closer look at munin, I did not know you could see statistics for each separate database in there. Thanks Colin!

**Comment by colinmollenhour** [comment]
I think I have a munin script for redis in my public gists or git repos.
