### ISSUE TITLE
Maintenance mode without maintenance.flag Due to use of Redis Session

### ISSUE THREAD

**Issue by kk98** [colinmollenhour/Cm_RedisSession#72]
My site goes on maintenance mode. I've check magento root folder there is not file maintenance.flag

I am using Redis Session extension. I am pretty sure that this extension did that. Now please help me how to disable maintenance mode.

I've disable that extension from app/etc/modules/cm_redis_session.xml

**Comment by colinmollenhour** [comment]
This is probably this feature kicking in:

* Limits the number of concurrent lock requests before a 503 error is returned.

This only affects the session that exceeds the limit, so other sessions are not necessarily affected. But if this is happening a lot then there is some issue causing it to happen which needs to be investigated, or you can change some settings to adjust the locking parameters if you are sure there are no fatal errors that would cause "zombie" locks.
