### ISSUE TITLE
Fall back to mysql / Carts being emptied

### ISSUE THREAD

**Issue by cdbessig** [colinmollenhour/Cm_RedisSession#75]
I didn't see it documented anywhere but it appears that if redis dies, the fallback to mysql will use the first_lifetime value.  So if you have this very short, you could be having customers whose carts are being flushed out after 10 minutes (600 seconds).

**Comment by colinmollenhour** [comment]
Hi Brian,

I don't think that was intentional, but the fallback feature is actually not well tested and probably should just be removed. IIRC the new version based on the abstracted layer removes the fallback feature.

**Comment by cdbessig** [comment]
Colin, Just to be clear, the new version of what exactly?  CM_RedisSession, or Magento 2, or what?

Thanks!

**Comment by colinmollenhour** [comment]
Check the "generic-adapter" branch which uses the generic adapter that was extracted out for use with Magento 2. Also the php56 branch removes the fallback. However, I don't remember why the php56 branch was never merged into master...
