### ISSUE TITLE
migrateSessions_mysql_redis.php when using compression will not work.

### ISSUE THREAD

**Issue by cdbessig** [colinmollenhour/Cm_RedisSession#76]
Looks like this line: 
https://github.com/colinmollenhour/Cm_RedisSession/blob/master/migrateSessions_mysql_redis.php#L51

Should use something else, perhaps _writeRawSession.  Will need to test and debug, but can say with certainty that when using gzip compression this migration script DOES not work and will cause errors such as: 
WRONGTYPE Operation against a key holding the wrong kind of value

In your var/report folder.

**Comment by colinmollenhour** [comment]
Looks like this was fixed.
