### ISSUE TITLE
Publish on Packagist

### ISSUE THREAD

**Issue by thaiphan** [colinmollenhour/Cm_RedisSession#79]
Hey Colin,

Would you be able to publish this extension on Packagist?

Regards,

Thai

**Comment by colinmollenhour** [comment]
Hi Thai,

Yes, I will publish it soon. Does the composer.json file work currently? (I don't use composer)

Also, I plan on making the generic-adapter branch the new master soon. It will be tagged as 2.0.

**Comment by thaiphan** [comment]
Yeah it works fine.

**Comment by colinmollenhour** [comment]
Ok I went ahead and published the current version as 1.14. Note, I renamed the package since there was a conflict with another unrelated pacakge on packagist.

**Comment by thaiphan** [comment]
Thanks!
