### ISSUE TITLE
Suggest Magento installer instead of requiring it

### ISSUE THREAD

**Issue by ToonSpinISAAC** [colinmollenhour/Cm_RedisSession#83]
Hi @colinmollenhour,

It's better to suggest the `magento-hackathon/magento-composer-installer` module instead of requiring it. That way, people can specify which version of the module they want, or a different installer altogether, and your version spec can't clash with other people's version spec; see the installer's author's thoughts on the matter [here](https://github.com/Cotya/magento-composer-installer/blob/3.0/doc/FAQ.md#should-my-module-require-the-installer).

In another Magento module, requiring instead of suggesting the installer has already caused problems for us and we've had to fork it, see [this PR](https://github.com/EcomDev/checkitout/pull/10) I made for details on why this was inconvenient for us in that specific case.

If you like, I'd be happy to make a PR.

Kind regards,

Toon

**Comment by colinmollenhour** [comment]
Thanks for the suggestion, Toon. I wasn't even aware of this option and it does indeed sound like an improvement so I'll gladly merge a PR.

**Comment by ToonSpinISAAC** [comment]
Thanks for merging @colinmollenhour!
