### ISSUE TITLE
Add the ability to bail from session read for bots

### ISSUE THREAD

**Issue by mpchadwick** [colinmollenhour/Cm_RedisSession#87]
Hey @colinmollenhour 

Would you be open to a PR that that allowed the user to configure behavior to bail from reading the session for bots? Session locks can become a real issue with bot traffic, and, really there's no reason they should need a session. On a project I work on at Something Digital we rewrote `Cm_RedisSession_Model_Session::read()` months ago to do this...

```php
public function read($sessionId)
{
    if ($this->_isBotToSkip()) {
        return false;
    }
    return parent::read($sessionId);
}
```

With some customization it looks like there's potentially [a way to tell Magento not to start the session](https://github.com/OpenMage/magento-mirror/blob/d409dff20e992e97546568974399c456958299f9/app/code/core/Mage/Core/Controller/Varien/Action.php#L488) but there's no guarantee something else (e.g. extensions, custom code) might not start the session anyway. As a failsafe, it might be a good idea to have the ability to just bail from reading the session for bots, if the implementor decides they would prefer that behavior. Additionally, if we handle it here, users could take advantage of the feature without customizing Magento at all. Plus, this module has already given some consideration to the impact of bots on sessions. What do you think?

**Comment by colinmollenhour** [comment]
I'm not completely opposed to the idea although it seems really risky to me.. E.g. what if GoogleBot starts using a session in some cases or a new legitimate user agent matches the regex? A less risky approach is to just disable locking which you can do on-the-fly like so:

```php
if (...) {
    define('CM_REDISSESSION_LOCKING_ENABLED', FALSE);
}
```

**Comment by mpchadwick** [comment]
In our case _isBotToSkip actually pulls from a different field which can be configured so as to not skip all bots. I currently can't think of a scenario where Google bot would need a session, but there may be something I'm overlooking. I could imagine getting into trouble with some cases where you do want bots to have sessions. Pingdom can do transactional checks and add to cart, for example. I'm also thinking about load testing tools like Gatling. The method you suggested is interesting, although in theory I'm thinking we could not only bail from read, but also write and even the constructor to prevent additional connections and writes. I'll try to work up a PR for further discussion regarding implementation. If you don't want to merge it in the end I won't be offended :smile:

**Comment by colinmollenhour** [comment]
Thanks, I will close this issue and consider your PR if/when it is submitted.
