### ISSUE TITLE
E_ERROR: Undefined Class Constant DEBUG

### ISSUE THREAD

**Issue by cdescampsx2i** [colinmollenhour/Cm_RedisSession#88]
Hello, I've got a problem, some requests finished with an error 503.

[Wed Jun 29 08:59:13 2016] [error] [client ] PHP Fatal error: Undefined class constant 'DEBUG' in /**/app/code/community/Cm/RedisSession/Model/Session.php on line 484

PHP 5.3.3-7
RedisSession 0.2
Redis server v=3.0.7

Same issue as : https://github.com/phpredis/phpredis/issues/857 and https://github.com/phpredis/phpredis/issues/534

**Comment by colinmollenhour** [comment]
I have seen similar issues but not this one exactly. Either the Zend_Log class is being unloaded during  shutdown before the session is closed or the autoloader is being unregistered before the session is closed. I'm not sure what is special about your setup that it happens to you but not others. Are you doing anything special with autoloaders?

If you want to submit a PR with the constants replaced with the real values an the constants in a comment only for the methods that happen during shutdown then I'd be happy to consider it. E.g.

```php
    if ($this->_logLevel >= 7) { // Zend_Log::DEBUG
```

However in the past when I've had similar issue there is often another issue that is the root and this is just a side-effect.
