### ISSUE TITLE
Multiple breaking of the same session lock

### ISSUE THREAD

**Issue by craigh1015** [colinmollenhour/Cm_RedisSession#92]
I am currently trying to diagnose an session locking problem similar to [session-lock-after-using-cm-redissession](http://magento.stackexchange.com/questions/133194/session-lock-after-using-cm-redissession). We have around 20 - 30 broken locks per hour.

In the process of diagnosing I have found that when multiple simultaneous requests end up blocking on an abandoned lock from different servers I see more than one of them break the lock. Even though the first lock breaker is resetting the PID.

Here is a sample log from redis-cli monitor:

1473467916.161853 [0 10.30.10.35:52498] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467916.162051 [0 10.30.10.35:52498] "HMGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "data" "writes"
1473467916.162421 [0 10.30.10.35:52498] "HMSET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid" "us-prod02-shopweb-01c.atl01.stelladotops.com|47157" "lock" "1" "req" "GET api-shop.stelladotprod02.com/style/b2c_en_ca/apiv1/cart/session"
1473467916.162444 [0 10.30.10.35:52498] "EXPIRE" "sess_0bp928v4o8ipo45qvhiiv3u106" "1209600"
1473467916.232871 [0 10.30.10.35:52498] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467916.233327 [0 10.30.10.35:52498] "HMSET" "sess_0bp928v4o8ipo45qvhiiv3u106" "data" "XXXX" "lock" "0"
1473467916.233373 [0 10.30.10.35:52498] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "writes" "1"
1473467916.233380 [0 10.30.10.35:52498] "EXPIRE" "sess_0bp928v4o8ipo45qvhiiv3u106" "1209600"
1473467924.493813 [0 10.30.10.35:36248] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467924.493984 [0 10.30.10.35:36248] "HMGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "data" "writes"
1473467924.494401 [0 10.30.10.35:36248] "HMSET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid" "us-prod02-shopweb-01c.atl01.stelladotops.com|49057" "lock" "1" "req" "GET api-shop.stelladot.com/style/b2c_en_ca/apiv1/catalog/summary"
1473467924.494426 [0 10.30.10.35:36248] "EXPIRE" "sess_0bp928v4o8ipo45qvhiiv3u106" "1209600"
1473467924.510282 [0 10.30.10.35:35630] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467924.510472 [0 10.30.10.35:35630] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "wait" "1"
1473467924.513382 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467924.513747 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "wait" "1"
1473467924.531701 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467924.531912 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "wait" "1"
1473467924.556643 [0 10.30.10.35:36248] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467924.557051 [0 10.30.10.35:36248] "HMSET" "sess_0bp928v4o8ipo45qvhiiv3u106" "data" "XXXX" "lock" "0"
1473467924.557100 [0 10.30.10.35:36248] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "writes" "1"
1473467924.557106 [0 10.30.10.35:36248] "EXPIRE" "sess_0bp928v4o8ipo45qvhiiv3u106" "1209600"
1473467925.020794 [0 10.30.10.35:35630] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467925.021039 [0 10.30.10.35:35630] "HMGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "data" "writes"
1473467925.021508 [0 10.30.10.35:35630] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "wait" "-1"
1473467925.021521 [0 10.30.10.35:35630] "HMSET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid" "us-prod02-shopweb-01c.atl01.stelladotops.com|49106" "lock" "1" "req" "GET api-shop.stelladot.com/style/b2c_en_ca/apiv1/catalog/categories"
1473467925.021540 [0 10.30.10.35:35630] "EXPIRE" "sess_0bp928v4o8ipo45qvhiiv3u106" "1209600"
1473467925.024079 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467925.042195 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467925.524611 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467925.542492 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467926.025155 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467926.042891 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467926.525653 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467926.543264 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467927.026051 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467927.043676 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467927.526475 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467927.544098 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467928.026920 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467928.044485 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467928.527253 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467928.544863 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467929.027645 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467929.045247 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467929.528115 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467929.545831 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467930.028601 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467930.046345 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467930.529107 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467930.546737 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467931.029653 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467931.047165 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467931.530077 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467931.547636 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467932.030514 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467932.048161 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467932.530949 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467932.548699 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467933.031383 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467933.049206 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467933.531868 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467933.549665 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467934.032354 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467934.032568 [0 10.30.10.36:37520] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467934.050132 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467934.050411 [0 10.30.10.35:42137] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467934.533020 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467934.550935 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467935.043519 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467935.061323 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467935.543907 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467935.561804 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467936.044303 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467936.062238 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467936.544729 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467936.562678 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467937.045185 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467937.063302 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467937.545566 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467937.563592 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467938.046043 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467938.063929 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467938.546453 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467938.564331 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467939.046878 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467939.064760 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467939.547211 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467939.565098 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467940.047659 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467940.065529 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467940.548166 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467940.565963 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467941.048642 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467941.067489 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467941.549110 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467941.568591 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467942.049477 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467942.069065 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467942.549955 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467942.569488 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467943.050343 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467943.069834 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467943.550692 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467943.570148 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467944.051091 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467944.051345 [0 10.30.10.36:37520] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467944.070741 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467944.071038 [0 10.30.10.35:42137] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467944.551804 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467944.571500 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467945.062265 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467945.081981 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467945.562722 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467945.582432 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467946.063173 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467946.082975 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467946.563703 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467946.583391 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467947.064195 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467947.083853 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467947.564629 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467947.584281 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467948.065089 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467948.084771 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467948.565498 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467948.585185 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467949.065958 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467949.085588 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467949.566433 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467949.585909 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467950.066947 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467950.086289 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467950.567461 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467950.586758 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467951.067985 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467951.087137 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467951.568420 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467951.587528 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467952.068841 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467952.087925 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467952.569254 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467952.588423 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467953.069826 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467953.088802 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467953.570255 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467953.589120 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467954.070734 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467954.070999 [0 10.30.10.36:37520] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467954.071250 [0 10.30.10.36:37520] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467954.089695 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467954.089973 [0 10.30.10.35:42137] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467954.090215 [0 10.30.10.35:42137] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467954.571663 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467954.571912 [0 10.30.10.36:37520] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467954.572160 [0 10.30.10.36:37520] "HMGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "data" "writes"
1473467954.573535 [0 10.30.10.36:37520] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "wait" "-1"
1473467954.573553 [0 10.30.10.36:37520] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "req"
1473467954.573561 [0 10.30.10.36:37520] "HMSET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid" "us-prod02-shopweb-02c.atl01.stelladotops.com|9906" "lock" "1" "req" "GET api-shop.stelladot.com/style/b2c_en_ca/apiv1/catalog/products"
1473467954.573578 [0 10.30.10.36:37520] "EXPIRE" "sess_0bp928v4o8ipo45qvhiiv3u106" "1209600"
1473467954.590613 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467954.590921 [0 10.30.10.35:42137] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467955.101349 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "lock" "1"
1473467955.101563 [0 10.30.10.35:42137] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid"
1473467955.101899 [0 10.30.10.35:42137] "HMGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "data" "writes"
1473467955.103228 [0 10.30.10.35:42137] "HINCRBY" "sess_0bp928v4o8ipo45qvhiiv3u106" "wait" "-1"
1473467955.103240 [0 10.30.10.35:42137] "HGET" "sess_0bp928v4o8ipo45qvhiiv3u106" "req"
1473467955.103247 [0 10.30.10.35:42137] "HMSET" "sess_0bp928v4o8ipo45qvhiiv3u106" "pid" "us-prod02-shopweb-01c.atl01.stelladotops.com|49190" "lock" "1" "req" "GET api-shop.stelladot.com/style/b2c_en_ca/apiv3/look"
1473467955.103267 [0 10.30.10.35:42137] "EXPIRE" "sess_0bp928v4o8ipo45qvhiiv3u106" "1209600"

**Comment by colinmollenhour** [comment]
Can you describe what you mean by "an abandoned lock"?

**Comment by craigh1015** [comment]
I have requests that are locking a session but never unlocking the session. This is then causing subsequent requests on the same session to have to wait until they break the lock. I am referring to this as an abandoned lock.

I am currently trying to track down if this might be caused by a failure to call the the __destruct() on the Session because a cycle of references exists.

**Comment by colinmollenhour** [comment]
Yes, I think you definitely want to figure out why the session is not getting unlocked. Possible causes would be a segfault in PHP, or possibly some types of fatal errors (like in the case of OOM I think it wouldn't have enough memory to complete the destroy). Unfortunately unlike the case with file locks or mysql locks if the process dies there is no way to handle it perfectly.

I suggest enabling the debug log with the "DEBUG" level as that should be a bit more informative than the raw redis log. E.g. you can distinguish between the reasons for why the "HINCRBY -1" occurred.
