### ISSUE TITLE
Missing lib folder

### ISSUE THREAD

**Issue by samuelecarpene** [colinmollenhour/Cm_RedisSession#96]
After installing with composer the master branch.

In master branch there is a problem with the "lib" missing folder.

Session model include some lib file that are missing.

`FastCGI: server "/home/httpd/www.buy-me.it/php5-www.buy-me.it-server" stderr: PHP message: PHP Fatal error:  require_once(): Failed opening required '/home/httpd/site-name/htdocs/app/code/local/Cm/RedisSession/Model/../lib/src/Cm/RedisSession/Handler/ConfigInterface.php' (include_path='/home/httpd/site-name/htdocs/app/code/local:/home/httpd/site-name/htdocs/app/code/community:/home/httpd/site-name/htdocs/app/code/core:/home/httpd/site-name/htdocs/lib:.:/usr/share/php:/usr/share/pear') in /home/httpd/site-name/htdocs/app/code/local/Cm/RedisSession/Model/Session.php on line 32`

**Comment by colinmollenhour** [comment]
Try adding the following to composer.json and let me know if that works:

```json
"require": {
  "colinmollenhour/php-redis-session-abstract": "~1.3"
}
```

**Comment by samuelecarpene** [comment]
I already downgraded to an old version so in my proejct is working well.
But if you use the master version you have this problem.

Thank you in advance.

**Comment by colinmollenhour** [comment]
I added the require to composer.json so I think it will work (tagged as 2.0.1) but do not have an environment handy to test with.

**Comment by SunshineTech** [comment]
After installing with modman the master branch. When do the following:
sudo php .modman/Cm_RedisSession/migrateSessions.php --test

there are the following errors:

PHP Fatal error:  require_once(): Failed opening required '/var/www/html/magento/lib/Cm/RedisSession/Handler/ConfigInterface.php' (include_path='/var/www/html/magento/app/code/local:/var/www/html/magento/app/code/community:/var/www/html/magento/app/code/core:/var/www/html/magento/lib:.:/usr/share/pear:/usr/share/php') in /var/www/html/magento/.modman/Cm_RedisSession/code/Model/Session/Handler.php on line 32

**Comment by colinmollenhour** [comment]
@SunshineTech It looks like your submodules are not present.. Both `modman clone` and `modman update` automatically update and init submodules so I wonder if you updated the module with git directly and not with the modman command? Regardless, make sure the submodules exist one way or another.

**Comment by Swahjak** [comment]
I think (since I am experiencing the same issue) it is related to installing modules with magento-hackathon/magento-composer-installer. Since this doesn't install the submodules. There is no way to get around this with the 'hard' require statements I think. Maybe add a check whether or not the required classes can be autoloaded before requiring them?
